name: wikilocal CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: Install npm.
        run: npm i
      - name: Lint files.
        run: npm run lint:js
      - name: Build app to check it builds correctly.
        run: npm run generate
      - name: Show message.
        run: echo "App lint and build correctly."
      - name: Upload files on server.
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.cicerone.guide
          username: admin@cicerone.guide
          password: ${{ secrets.FTP_CICERONE_PASSWORD }}
          local-dir: dist/
          server-dir: ./cicerone.guide/public_html/
