name: wikilocal CI

on:
  pull_request:
    branches: [ main ]

jobs:
  pull_request:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm.
        run: npm i
      - name: Lint files.
        run: npm run lint:js
      #- name: Test functionalities/implementations.
      #  run: npm test
      - name: Build app to check it builds correctly.
        run: npm run generate
      - name: Show message.
        run: echo "All tests passed, app lint and build correctly."
      - name: Upload files on server.
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.wikilocal.pukara.es
          username: wikilocal-admin@wikilocal.pukara.es
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ./wikilocal.pukara.es/public_html/
